### ISSUE TITLE
Page crashes

### ISSUE THREAD

**Issue by r00teniy** [kepstin/Fix-pixiv-thumbnails#3]
Hello this script crashes discovery page then you mouseover any username, i recommend excluding https://www.pixiv.net/discovery*

**Comment by kepstin** [comment]
Hi, I am not able to reproduce this issue… Mouseover of username on the Discovery page works fine for me:
![Screenshot from 2020-05-09 20-11-21](https://user-images.githubusercontent.com/38788/81487986-6f810280-9231-11ea-968e-edfd6277be0b.png)
As you can see, it even fixes cropped thumbnails on the popup.

Can you please describe exactly what happens? Also please share:
* What web browser are you using? What version?
* The web inspector console logs

**Comment by r00teniy** [comment]
Just checked and it works on Firefox, but crashes on Chrome somehow.  Could you please confirm that if also works on Chrome so i can start looking for problems in my Chrome setup?

**Comment by kepstin** [comment]
I've managed to reproduce the error in Chrome. There appears to be something wrong with the generation of the CSS image-set string, I'm getting this exception:
```
Improve pixiv thumbnails.user.js:93 Uncaught RangeError: Invalid string length
    at Array.join (<anonymous>)
    at cssImageSet (Improve pixiv thumbnails.user.js:93)
    at handleABackground (Improve pixiv thumbnails.user.js:223)
    at MutationObserver.mutationObserverCallback (Improve pixiv thumbnails.user.js:273)
cssImageSet @ Improve pixiv thumbnails.user.js:93
handleABackground @ Improve pixiv thumbnails.user.js:223
mutationObserverCallback @ Improve pixiv thumbnails.user.js:273
```
which seems to be causing a lockup in the mutation observer callback. It looks like if you move your mouse off the username it will eventually timeout and the page will start working again.

Hopefully I can look at fixing the issue later today. Note that the "discovery" page is not the only page affected - other pages with user popups also have this problem.

**Comment by kepstin** [comment]
I have fixed the issue by correcting a regular expression match that caused looping behaviour. The update has been pushed to greasyfork, you should receive the update shortly (or you can manually hit update in your userscript manager).

**Comment by r00teniy** [comment]
Thank you.
